import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const nanumSquare = localFont({
  src: [
    {
      path: "../../public/font/NanumSquareR.otf",
      weight: "400",
      style: "regular",
    },
    {
      path: "../../public/font/NanumSquareB.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-nanum-square",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${nanumSquare.className} ${nanumSquare.variable}`}>
        {children}
      </body>
    </html>
  );
}
